### ISSUE TITLE
Question about the performance with photometric consistency only

### ISSUE THREAD

**Issue by XYZ-qiyh** [ToughStoneX/U-MVS#3]
Hi @ToughStoneX 
Thanks for your amazing work on unsupervised MVS.
I have one doubt about the performance when the model is trained with photometric consistency (denoted as _Lpc_ in your paper) only.
In JDACS, MVSNet with _Lpc_ achieved 0.7215/0.6339/0.6777 on Acc./Comp./Overall, respectively.
In U-MVS, MVSNet with _Lpc_ achieved 0.5527/0.5345/0.5436 on Acc./Comp./Overall, respectively.

Is there any difference in experimental settings? 
Or, the modified photometric consistency _Lpc'_ is adopted in U-MVS instead of the original _Lpc_ ?

Looking forward to your reply.
Many thanks!

**Comment by ToughStoneX** [comment]
Yes, some modifications are added to the base code of JDACS. They are summarized as follows:

1, Issues about the image normalization scheme. 
In the original code of JDACS, there is a function named as [center_image](https://github.com/ToughStoneX/Self-Supervised-MVS/blob/9fe7394f0d7a0d655b48aac82717145e8ef62871/jdacs/datasets/dtu_yao.py#L94). 
```python
def center_image(self, img):
      """ normalize image input """
      img = img.astype(np.float32)
      var = np.var(img, axis=(0, 1), keepdims=True)
      mean = np.mean(img, axis=(0, 1), keepdims=True)
      return (img - mean) / (np.sqrt(var) + 0.00000001)
```
The loaded image is firstly preprocessed with this `center_image` function in JDACS. On the one hand, the multi-view images are fed to the MVSNet model and return the depth map. On the other hand, these images are also fed to the mentioned Lpc to calculate the photometric consistency loss. 
However, in U-MVS, the images fed to the MVSNet model is handled by transformation of the mean and variance values calculated from imagenet, as follows:
```
from torchvision import transforms

self.transform_img = transforms.Compose([
      transforms.ToTensor(),
      transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])
```
Since sometimes the black area in the background and white area in the table may interrupt the mean value on different views in this `center_image` function, we replace it with the aforementioned transform in the above codes. 
For example, consider the case that the following images are being processed.

<figure class="half">
    <img src="https://user-images.githubusercontent.com/25602587/146752619-bc4449cb-d23b-476a-a4d5-f87777c5b361.jpg" width=300/>
    <img src="https://user-images.githubusercontent.com/25602587/146752642-54776c66-30a5-43f4-abc6-cf03dee9b399.jpg" width=300/>
</figure >

If these images are processed by `center_image` function, you may find out that the color distributions are totally different. Because they have different mean and variance values. Whereas these transformations may break the color consistency relationship in the corresponding regions among views.
This `center_image` may include dispensable degradation of performance, hence it is removed in U-MVS.

2, Another modification is the mentioned Lpc' in the paper.
Some modifications for estimating aleatoric and epistemic uncertainty are added.
You may find more details in the [supplementary material](https://arxiv.org/pdf/2108.12966.pdf) (Figure 9) of the paper.

**Comment by XYZ-qiyh** [comment]
Thanks for your detailed explanation.
