### ISSUE TITLE
each "final3d_model.ply" is only 4k

### ISSUE THREAD

**Issue by AddASecond** [ToughStoneX/U-MVS#5]
Hi, when reproducing u_mvs_mvsnet, it is very confusing for me that:
whether I use pretrained model / self_pretrained model,
after run test_pretrain.sh, the final3d_model.ply for every scan are both only 4k

some log is as followings:
`Processing camera 44
Found 0.00 million points
Processing camera 45
Found 0.00 million points
Processing camera 46
Found 0.00 million points
Processing camera 47
Found 0.00 million points
Processing camera 48
Found 0.00 million points
		ELAPSED 2.416907 seconds
Error: no kernel image is available for execution on the device
Writing ply file ./outputs/scan118/points_mvsnet//consistencyCheck-20220215-174227//final3d_model.ply
store 3D points to ply file
/home/softwares/anaconda3_gy/lib/python3.8/site-packages/torch/nn/functional.py:3981: UserWarning: Default grid_sample and affine_grid behavior has changed to align_corners=False since 1.3.0. Please specify align_corners=True if the old behavior is desired. See the documentation of grid_sample for details.
  warnings.warn(

Convert mvsnet output to gipuma input
Run depth map fusion & filter
./fusion/fusibile/build/fusibile -input_folder ./outputs/scan11/points_mvsnet/ -p_folder ./outputs/scan11/points_mvsnet/cams/ -images_folder ./outputs/scan11/points_mvsnet/images/ --depth_min=0.001 --depth_max=100000 --normal_thresh=360 --disp_thresh=0.3 --num_consistent=3.0`

**Comment by ToughStoneX** [comment]
Hi. I notice that there is an error reported in the log you provide: `Error: no kernel image is available for execution on the device`. In my experience, this error usually occurs when the `fusibile` is not built correctly and cannot find an executable file to run the code. In this case, you may find that an empty `ply` file is generated. 
Here are some suggestions:
1, Have you built the executable file following the instructions in https://github.com/ToughStoneX/U-MVS/tree/main/u_mvs_mvsnet#fusion? Some basic matters which requires attention are listed here.
2, A typical case reporting this error is because of the inappropriate setting of gpu architecture in the provided `CMakeLists.txt`. The provided code is built under Tesla V100 in default. If you want to build the code yourself, you should make sure the corresponding setting of GPU architecture in `CMakeLists.txt` is modified accordingly. Please refer to more detailed information in https://github.com/ToughStoneX/U-MVS/tree/main/u_mvs_mvsnet#fusion.

**Comment by AddASecond** [comment]
Hi thanks 
changing gpu compute capabilities solves the problem, now each ply file is about 402M

this website can check gpu compte capabilities
https://developer.nvidia.com/cuda-gpus

for example, my GPU is 3080 so I add this line to CMakeLists.txt in fusible:
`# 3080 10G
set(CUDA_NVCC_FLAGS ${CUDA_NVCC_FLAGS};-O3 --use_fast_math --ptxas-options=-v -std=c++11 --compiler-options -Wall -gencode arch=compute_86,code=sm_86 -gencode arch=compute_86,code=sm_86)`
